version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-gtmotive
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gtmotive
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
